wokspaceRails/primera_app/config/routes.rb
Rails.application.routes.draw do
  get 'generates/x'

  get 'generates/y'

  get 'generates/z'

  get 'boxes/index'

  get 'boxes/error'

  get 'boxes/content'

  get 'pages/index'

  get 'pages/about'

  get 'pages/contact'

  root 'generates#x'

end

wokspaceRails/primera_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	before_action :get_array

	def get_array
		@arregloNumeros = [1,2,3,4,5,6,7,8,9]
	end
end

wokspaceRails/primera_app/app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  def index
  end

  def error
  end

  def content
  end
end

wokspaceRails/primera_app/app/controllers/generates_controller.rb
class GeneratesController < ApplicationController
	before_action :get_array

	def get_array
		@arregloNumeros = [1,2,3,4,5,6,7,8,9]
	end

  def x
  	@hello = "Hola Mundo"

  	@arreglo = ['Leovi', 'Pedro', 'Paco', 'Axel']
  end

  def y
  end

  def z
  end
end

wokspaceRails/primera_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

wokspaceRails/primera_app/app/helpers/application_helper.rb
module ApplicationHelper
end

wokspaceRails/primera_app/app/helpers/boxes_helper.rb
module BoxesHelper
end

wokspaceRails/primera_app/app/helpers/generates_helper.rb
module GeneratesHelper
end

wokspaceRails/primera_app/app/helpers/pages_helper.rb
module PagesHelper
end

wokspaceRails/primera_app/app/views/boxes/content.html.erb
<h1>Boxes#content</h1>
<p>Find me in app/views/boxes/content.html.erb</p>

wokspaceRails/primera_app/app/views/boxes/error.html.erb
<h1>Boxes#error</h1>
<p>Find me in app/views/boxes/error.html.erb</p>

wokspaceRails/primera_app/app/views/boxes/index.html.erb
<h1>Boxes#index</h1>
<p>Find me in app/views/boxes/index.html.erb</p>

wokspaceRails/primera_app/app/views/generates/x.html.erb
<h1>Generates#x</h1>
<p>Find me in app/views/generates/x.html.erb</p>
<%= @hello %>

<%@arreglo.each do |group|%>
<%=group%>
<%end%>

<%@arregloNumeros.each do |group|%>
<%=group%>
<%end%>

wokspaceRails/primera_app/app/views/generates/y.html.erb
<h1>Generates#y</h1>
<p>Find me in app/views/generates/y.html.erb</p>


<%@arregloNumeros.each do |group|%>
<%=group%>
<%end%>

wokspaceRails/primera_app/app/views/generates/z.html.erb
<h1>Generates#z</h1>
<p>Find me in app/views/generates/z.html.erb</p>

<%@arregloNumeros.each do |group|%>
<%=group%>
<%end%>

wokspaceRails/primera_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrimeraApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<ul>
		<li><%= link_to "HOME", root_path%></li>
		<li><%= link_to "x", generates_x_path %></li>
		<li><%= link_to "y", generates_y_path %></li>
		<li><%= link_to "z", generates_z_path%></li>
	</ul>
<%= yield %>

</body>
</html>

wokspaceRails/primera_app/app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

wokspaceRails/primera_app/app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

wokspaceRails/primera_app/app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>